### ISSUE TITLE
关于启动ucore的一些问题

### ISSUE THREAD

**Issue by SeddonShen** [TwistsOfFate/vanilla-cpu#1]
学长你们好，现在我们在参加 NSCSCC2021 ,在启动 Ucore 的时候出现了一些问题。
首先，我们在使用soc_up_33M.bit（龙芯给的Demo的核）启动UCore的时候，是启动不起来的，我们用的是资源包里给的默认的ucore-kernel-initrd，使用tftp进行load，但是会在load完成之后报错卡死。
具体的操作如下:
```
PMON>g console=ttyS0,57600 rdinit=sbin/init 
   zero      at       v0       v1       a0       a1       a2       a3   
 00000000 00000000 00000000 00000000 00000003 a7dffd78 a7dffd88 870af430
    t0       t1       t2       t3       t4       t5       t6       t7   
 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    s0       s1       s2       s3       s4       s5       s6       s7   
 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    t8       t9       k0       k1       gp       sp       s8       ra   
 00000000 00000000 00000000 00000000 00000000 a7dffd58 00000000 8707ac38
```
我们怀疑资源包里面给的ucore是有问题的，在拜读您队伍的ucore启动流程的时候发现您是重新修改了ucore的代码并重新进行编译，所以请问您去年是不是也遇到了相关的问题，或者说您为什么要自己重新编译ucore呢？
谢谢！

**Comment by TwistsOfFate** [comment]
很抱歉由于时间久远，很多细节和步骤都记不清了，恐怕无法给予你具体的建议。

印象中，官方提供的 soc_up_33M.bit 确实无法启动 uCore，这可能是因为它不能支持所有 uCore 运行需要的指令。可以考虑进行探索：

- ucore-kernel-initrd 的源码中用到了指令集中的哪些指令

- soc_up_33M.bit 代表的处理器支持哪些指令

**Comment by SeddonShen** [comment]
感谢学长！
